// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping.proto

package pingpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PingResponse struct {
	Number               int64    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FailRequest struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailRequest) Reset()         { *m = FailRequest{} }
func (m *FailRequest) String() string { return proto.CompactTextString(m) }
func (*FailRequest) ProtoMessage()    {}
func (*FailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{2}
}

func (m *FailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailRequest.Unmarshal(m, b)
}
func (m *FailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailRequest.Marshal(b, m, deterministic)
}
func (m *FailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailRequest.Merge(m, src)
}
func (m *FailRequest) XXX_Size() int {
	return xxx_messageInfo_FailRequest.Size(m)
}
func (m *FailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FailRequest proto.InternalMessageInfo

func (m *FailRequest) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type FailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailResponse) Reset()         { *m = FailResponse{} }
func (m *FailResponse) String() string { return proto.CompactTextString(m) }
func (*FailResponse) ProtoMessage()    {}
func (*FailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{3}
}

func (m *FailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailResponse.Unmarshal(m, b)
}
func (m *FailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailResponse.Marshal(b, m, deterministic)
}
func (m *FailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailResponse.Merge(m, src)
}
func (m *FailResponse) XXX_Size() int {
	return xxx_messageInfo_FailResponse.Size(m)
}
func (m *FailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FailResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingRequest)(nil), "rerpc.ping.v0.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "rerpc.ping.v0.PingResponse")
	proto.RegisterType((*FailRequest)(nil), "rerpc.ping.v0.FailRequest")
	proto.RegisterType((*FailResponse)(nil), "rerpc.ping.v0.FailResponse")
}

func init() { proto.RegisterFile("ping.proto", fileDescriptor_6d51d96c3ad891f5) }

var fileDescriptor_6d51d96c3ad891f5 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcc, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x4a, 0x2d, 0x2a, 0x48, 0xd6, 0x03, 0x8b,
	0x94, 0x19, 0x28, 0xa9, 0x72, 0x71, 0x07, 0x64, 0xe6, 0xa5, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x89, 0x71, 0xb1, 0xe5, 0x95, 0xe6, 0x26, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0x30, 0x07, 0x41, 0x79, 0x4a, 0x6a, 0x5c, 0x3c, 0x10, 0x65, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x48, 0xea, 0x98, 0x50, 0xd4, 0x29, 0x72, 0x71, 0xbb, 0x25, 0x66, 0xe6, 0xc0, 0x8c, 0x13, 0xe2,
	0x62, 0x49, 0xce, 0x4f, 0x49, 0x85, 0x1a, 0x06, 0x66, 0x2b, 0xf1, 0x71, 0xf1, 0x40, 0x94, 0x40,
	0x8c, 0x32, 0xea, 0x61, 0xe4, 0x62, 0x01, 0x99, 0x2d, 0xe4, 0x08, 0xa5, 0xa5, 0xf4, 0x50, 0x9c,
	0xa8, 0x87, 0xe4, 0x3e, 0x29, 0x69, 0xac, 0x72, 0x10, 0x93, 0x94, 0x18, 0x40, 0x46, 0x80, 0xcc,
	0xc6, 0x30, 0x02, 0xc9, 0x4d, 0x18, 0x46, 0x20, 0x3b, 0x46, 0x89, 0xc1, 0x89, 0x23, 0x8a, 0x0d,
	0x24, 0x53, 0x90, 0x94, 0xc4, 0x06, 0x0e, 0x30, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04,
	0xaf, 0x64, 0x31, 0x3e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingClient is the client API for Ping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/rerpc.ping.v0.Ping/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*FailResponse, error) {
	out := new(FailResponse)
	err := c.cc.Invoke(ctx, "/rerpc.ping.v0.Ping/Fail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServer is the server API for Ping service.
type PingServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Fail(context.Context, *FailRequest) (*FailResponse, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rerpc.ping.v0.Ping/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rerpc.ping.v0.Ping/Fail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rerpc.ping.v0.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Ping_Ping_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _Ping_Fail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping.proto",
}
