name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 22 * * *'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          lfs: true
      - name: Test
        run: make test
      - name: Lint
        if: matrix.go-version == '1.16.x'
        run: make lint
